### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by dscho** [fiji/Fiji_Package_Maker#1]
@ctrueden @hinerm I do not know what the current procedure is (pre-emptively bump? Bump through Jenkins? Something else?), so may I ask one of you to release and upload with the new `Include Java Runtime` option?

**Comment by ctrueden** [comment]
@dscho Sure!

Regarding preemptive parent bumps and such, at the moment we are doing things manually. So here are the steps I just performed:
- Bumped `Fiji_Package_Maker.version` in `pom-fiji` to `2.1.0` (before releasing it). (https://github.com/fiji/pom-fiji/commit/013931b1f0bc3be58938ca06c81e6c7d9c9b0a77)
- Released `pom-fiji` version `6.6.0` using the Jenkins Release-Version job.
- Updated `Fiji_Package_Maker` POM to extend that version `6.6.0`. (8f3c9b86d5c8eb2b1d333ef6445cec240e808052)
- Released `Fiji_Package_Maker` version `2.1.0` using the `release-version.sh` shell script from `dev`. (Because we have not added all 100+ Fiji components to the Jenkins Release-Version job, and I am on the fence about whether we ever should.)

For that last point, the other option is the double-push-to-master approach. This works well thanks to the enforcer plugin catching any grievous configuration problems, and is how many Fiji plugins accomplish their releases now. But personally I still prefer `release-version.sh` since it tags each release properly.

Then:
- Bumped the `pom-fiji` parent of `fiji` itself to version `6.6.0`. (https://github.com/fiji/fiji/commit/105e262e3428cb75f29561c4877e724251759e96) So now when you build Fiji from source (for some definition of "build" :wink:), it includes the `Fiji_Package_Maker` version `2.1.0` release.
- Uploaded the latest Fiji components to the Fiji update site using `mvn -Dimagej.app.directory=/Applications/Fiji.app` followed by the upload (ignoring a couple of minor discrepancies, which is needed in the short term since `fiji.git` and the Fiji update site are not yet 100% aligned—although they grow increasingly closer; see https://github.com/fiji/fiji/issues/39).

A couple of related notes:
- As you know, we still want more tooling some day to automate much of this. But for the next few months we are hoping to focus a lot more on development, since the project structure is pretty stable now.
- Relatedly, as I mentioned to you at the hackathon, I want Jenkins to automatically upload the current state of `fiji` `master` branch to the Fiji update site. And eliminate direct push access to the `fiji` repository itself for Fiji plugin developers, as well as direct upload access to the Fiji update site, in favor of pull requests. Trusted folks who understand how things work and want more rapid turnaround time can of course have push access to `fiji` again, with the understanding that they are taking on a shared "maintainer" role by doing so.
